defaults:
  - _self_

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-imagenet100-linear"
pretrained_feature_extractor: None
backbone:
  name: "resnet18"
method: "dino"
dataset: imagenet100
dataset_dir: "/buckets/ml/datasets"
data:
  dataset: imagenet100
  train_path: "./datasets/imagenet-100/train"
  val_path: "./datasets/imagenet-100/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 250
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
