repr: "dinov2"
dataset: "mnist"
num_classes: 10
root_dir: "/buckets/ml"
batch_size: 2048
beta: 100.0
lr: 0.0001
weight_decay: 1e-7
k: 100
num_layers: 1
num_hidden_units: 512
gammma: 0.8
num_iter: 500
eval_interval: 50
